//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 12:09:20 AM IST 
//


package com.google.finance.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.google.finance.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.google.finance.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance }
     * 
     */
    public XmlApiReply.Finance createXmlApiReplyFinance() {
        return new XmlApiReply.Finance();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Low }
     * 
     */
    public XmlApiReply.Finance.Low createXmlApiReplyFinanceLow() {
        return new XmlApiReply.Finance.Low();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.DaylightSavings }
     * 
     */
    public XmlApiReply.Finance.DaylightSavings createXmlApiReplyFinanceDaylightSavings() {
        return new XmlApiReply.Finance.DaylightSavings();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.SymbolUrl }
     * 
     */
    public XmlApiReply.Finance.SymbolUrl createXmlApiReplyFinanceSymbolUrl() {
        return new XmlApiReply.Finance.SymbolUrl();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.BrutTradeDateUtc }
     * 
     */
    public XmlApiReply.Finance.BrutTradeDateUtc createXmlApiReplyFinanceBrutTradeDateUtc() {
        return new XmlApiReply.Finance.BrutTradeDateUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Symbol }
     * 
     */
    public XmlApiReply.Finance.Symbol createXmlApiReplyFinanceSymbol() {
        return new XmlApiReply.Finance.Symbol();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.BrutLast }
     * 
     */
    public XmlApiReply.Finance.BrutLast createXmlApiReplyFinanceBrutLast() {
        return new XmlApiReply.Finance.BrutLast();
    }

    /**
     * Create an instance of {@link XmlApiReply }
     * 
     */
    public XmlApiReply createXmlApiReply() {
        return new XmlApiReply();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.IsldLast }
     * 
     */
    public XmlApiReply.Finance.IsldLast createXmlApiReplyFinanceIsldLast() {
        return new XmlApiReply.Finance.IsldLast();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.DisclaimerUrl }
     * 
     */
    public XmlApiReply.Finance.DisclaimerUrl createXmlApiReplyFinanceDisclaimerUrl() {
        return new XmlApiReply.Finance.DisclaimerUrl();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.CurrentTimeUtc }
     * 
     */
    public XmlApiReply.Finance.CurrentTimeUtc createXmlApiReplyFinanceCurrentTimeUtc() {
        return new XmlApiReply.Finance.CurrentTimeUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Divisor }
     * 
     */
    public XmlApiReply.Finance.Divisor createXmlApiReplyFinanceDivisor() {
        return new XmlApiReply.Finance.Divisor();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Company }
     * 
     */
    public XmlApiReply.Finance.Company createXmlApiReplyFinanceCompany() {
        return new XmlApiReply.Finance.Company();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.ExchangeClosing }
     * 
     */
    public XmlApiReply.Finance.ExchangeClosing createXmlApiReplyFinanceExchangeClosing() {
        return new XmlApiReply.Finance.ExchangeClosing();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Open }
     * 
     */
    public XmlApiReply.Finance.Open createXmlApiReplyFinanceOpen() {
        return new XmlApiReply.Finance.Open();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.TradeTimeUtc }
     * 
     */
    public XmlApiReply.Finance.TradeTimeUtc createXmlApiReplyFinanceTradeTimeUtc() {
        return new XmlApiReply.Finance.TradeTimeUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.YClose }
     * 
     */
    public XmlApiReply.Finance.YClose createXmlApiReplyFinanceYClose() {
        return new XmlApiReply.Finance.YClose();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.IsldTradeTimeUtc }
     * 
     */
    public XmlApiReply.Finance.IsldTradeTimeUtc createXmlApiReplyFinanceIsldTradeTimeUtc() {
        return new XmlApiReply.Finance.IsldTradeTimeUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Currency }
     * 
     */
    public XmlApiReply.Finance.Currency createXmlApiReplyFinanceCurrency() {
        return new XmlApiReply.Finance.Currency();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.ExchangeUtcOffset }
     * 
     */
    public XmlApiReply.Finance.ExchangeUtcOffset createXmlApiReplyFinanceExchangeUtcOffset() {
        return new XmlApiReply.Finance.ExchangeUtcOffset();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.TradeTimestamp }
     * 
     */
    public XmlApiReply.Finance.TradeTimestamp createXmlApiReplyFinanceTradeTimestamp() {
        return new XmlApiReply.Finance.TradeTimestamp();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.ChartUrl }
     * 
     */
    public XmlApiReply.Finance.ChartUrl createXmlApiReplyFinanceChartUrl() {
        return new XmlApiReply.Finance.ChartUrl();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.ExchangeTimezone }
     * 
     */
    public XmlApiReply.Finance.ExchangeTimezone createXmlApiReplyFinanceExchangeTimezone() {
        return new XmlApiReply.Finance.ExchangeTimezone();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.MarketCap }
     * 
     */
    public XmlApiReply.Finance.MarketCap createXmlApiReplyFinanceMarketCap() {
        return new XmlApiReply.Finance.MarketCap();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.SymbolLookupUrl }
     * 
     */
    public XmlApiReply.Finance.SymbolLookupUrl createXmlApiReplyFinanceSymbolLookupUrl() {
        return new XmlApiReply.Finance.SymbolLookupUrl();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Volume }
     * 
     */
    public XmlApiReply.Finance.Volume createXmlApiReplyFinanceVolume() {
        return new XmlApiReply.Finance.Volume();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.IsldTradeDateUtc }
     * 
     */
    public XmlApiReply.Finance.IsldTradeDateUtc createXmlApiReplyFinanceIsldTradeDateUtc() {
        return new XmlApiReply.Finance.IsldTradeDateUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.CurrentDateUtc }
     * 
     */
    public XmlApiReply.Finance.CurrentDateUtc createXmlApiReplyFinanceCurrentDateUtc() {
        return new XmlApiReply.Finance.CurrentDateUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.TradeDateUtc }
     * 
     */
    public XmlApiReply.Finance.TradeDateUtc createXmlApiReplyFinanceTradeDateUtc() {
        return new XmlApiReply.Finance.TradeDateUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Change }
     * 
     */
    public XmlApiReply.Finance.Change createXmlApiReplyFinanceChange() {
        return new XmlApiReply.Finance.Change();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.High }
     * 
     */
    public XmlApiReply.Finance.High createXmlApiReplyFinanceHigh() {
        return new XmlApiReply.Finance.High();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.EcnUrl }
     * 
     */
    public XmlApiReply.Finance.EcnUrl createXmlApiReplyFinanceEcnUrl() {
        return new XmlApiReply.Finance.EcnUrl();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Exchange }
     * 
     */
    public XmlApiReply.Finance.Exchange createXmlApiReplyFinanceExchange() {
        return new XmlApiReply.Finance.Exchange();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Last }
     * 
     */
    public XmlApiReply.Finance.Last createXmlApiReplyFinanceLast() {
        return new XmlApiReply.Finance.Last();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.PrettySymbol }
     * 
     */
    public XmlApiReply.Finance.PrettySymbol createXmlApiReplyFinancePrettySymbol() {
        return new XmlApiReply.Finance.PrettySymbol();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.AvgVolume }
     * 
     */
    public XmlApiReply.Finance.AvgVolume createXmlApiReplyFinanceAvgVolume() {
        return new XmlApiReply.Finance.AvgVolume();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.Delay }
     * 
     */
    public XmlApiReply.Finance.Delay createXmlApiReplyFinanceDelay() {
        return new XmlApiReply.Finance.Delay();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.BrutTradeTimeUtc }
     * 
     */
    public XmlApiReply.Finance.BrutTradeTimeUtc createXmlApiReplyFinanceBrutTradeTimeUtc() {
        return new XmlApiReply.Finance.BrutTradeTimeUtc();
    }

    /**
     * Create an instance of {@link XmlApiReply.Finance.PercChange }
     * 
     */
    public XmlApiReply.Finance.PercChange createXmlApiReplyFinancePercChange() {
        return new XmlApiReply.Finance.PercChange();
    }

}
